version: "3.8"

services:
  deepfacelab:
    image: deepfacelab-gpu
    build: .
    container_name: deepfacelab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/workspace/DeepFaceLab
    working_dir: /workspace/DeepFaceLab
    command: /bin/bash
