version: '3.8'

services:
  deepfacelab:
    build: .
    container_name: deepfacelab
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./workspace:/workspace
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    stdin_open: true
    tty: true
    restart: unless-stopped
