services:
  deepfacelab:
    image: deepfacelab-gpu
    build: .
    container_name: deepfacelab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/DeepFaceLab
    working_dir: /DeepFaceLab
    stdin_open: true  # ✅ Keeps the container open for interaction
    tty: true         # ✅ Prevents the container from exiting immediately
    command: /bin/bash
